name: CS-Halloween-Event
main: me.kevsal.minecraft.cshalloween.Main
version: 1.0-SNAPSHOT
author: Kevinsal03
description: Halloween event for ClubSurvival

commands:
  event:
    description: Get event details
    aliases: [server-event, halloween, halloween-event]
    usage: /<command>
#disable-event:
#  description: Disable the plugin
#  permission: cs.event.op
#  usage: /<command>

permissions:
  cs.event.op:
    default: op